### ISSUE TITLE
Missing link to word2vec from What are Embeddings book

### ISSUE THREAD

**Issue by justinhj-td** [veekaybee/viberary#102]
I've noticed some of the links from the book What are Embeddings are no longer found in this repository. For example:

https://github.com/veekaybee/viberary/tree/main/word2vec
(from page 46 in the word2vec section)

Is there a branch or tag I could use to find it?

**Comment by veekaybee** [comment]
Thanks! This should be fixed with this:  https://github.com/veekaybee/what_are_embeddings/issues/28
