### ISSUE TITLE
Pass `start` argument to `enumerate` for search

### ISSUE THREAD

**Issue by pmbaumgartner** [veekaybee/viberary#25]
https://github.com/veekaybee/viberary/blob/7e326677a063cd90c593865d975443b395b51fd0/src/models/bert/knn_search.py#L81

`enumerate` [takes a second argument](https://docs.python.org/3/library/functions.html#enumerate), `start`, which can be used to start the enumeration at a non-zero value. I think you want to set this to `1` for display purposes in the template, so this line would be:

```python
        return [(val[2], index) for index, val in enumerate(result_list, 1)]
```

**Comment by veekaybee** [comment]
Yep, will fix this other issue once I have time, thanks for this. https://github.com/veekaybee/viberary/issues/20
