### ISSUE TITLE
Long long time for docker compose up

### ISSUE THREAD

**Issue by amy-tabb** [veekaybee/viberary#38]
Hello Vicki, I got around to testing the latest release on my machine (0.0.3) .... and currently it seems I am stalled out on the docker compose up step. Are these times typical?

![Screenshot from 2023-07-03 15-41-34](https://github.com/veekaybee/viberary/assets/25328047/5ad3dfa8-4fca-43e3-8d4f-6ffa2d2bb3fc)

**Comment by veekaybee** [comment]
Nope, it should take less than a minute to stand everything up. Looks like the build command worked correctly. What do you get when you run `docker compose --verbose up`?

**Comment by veekaybee** [comment]
@amy-tabb let me know if you're still having issues, otherwise closing this out as I've released a new version
