### ISSUE TITLE
Feature: Share Results?

### ISSUE THREAD

**Issue by cogdog** [veekaybee/viberary#96]
Having fun trying the vibes! As a user, it might be nice to be able to share a search result, send to a friend, let them maybe modify?

Oh, on inspecting the buttons, I can see how to manually create a sharable link

https://viberary.pizza/search?query=smart+talking+animals

**Comment by veekaybee** [comment]
@cogdog Thanks! Yep the search route should have the query string available. Let me know if that resolves the issue and I can close it.

**Comment by cogdog** [comment]
Hmmmm, not seeing any difference. Seems like it works if you change form method from POST to GET.

**Comment by veekaybee** [comment]
@cogdog Just shipped a fix to this, try it out now :) Thanks for the feedback!

**Comment by cogdog** [comment]
Works perfectly, just searched and saved http://viberary.pizza/search/results?query=Animals+on+boatsAgain much appreciation for how much you explain what’s happening behind the scenes.Alan Levinecog.dog • cogdogblog.com  • cogdog.infoOn Aug 6, 2023, at 5:23 AM, Vicki Boykis ***@***.***> wrote:﻿
@cogdog Just shipped a fix to this, try it out now :) Thanks for the feedback!
